src/com/asiainfo/ocmanager/dacp/DacpAllResult.java
src/com/asiainfo/ocmanager/dacp/dacpForResourceUtil.java
src/com/asiainfo/ocmanager/rest/resource/quotaUtils/quotaQuery.java

dacp优化  mongo优化

---

src/com/asiainfo/ocmanager/mail/ParamQuery.java

hive kerberos串优化

---

src/com/asiainfo/ocmanager/dacp/dacpForResourceUtil.java

去掉部分组件信息（传给dacp）

---

src/com/asiainfo/ocmanager/persistence/mapper/TenantUserRoleAssignmentMapper.java
src/com/asiainfo/ocmanager/persistence/mapper/TenantUserRoleAssignmentMapper.xml
src/com/asiainfo/ocmanager/persistence/test/TestTenantUserRoleAssignment.java
src/com/asiainfo/ocmanager/rest/bean/UserRoleViewBean.java
src/com/asiainfo/ocmanager/rest/bean/UserWithTURBean.java
src/com/asiainfo/ocmanager/rest/constant/Constant.java
src/com/asiainfo/ocmanager/rest/resource/TenantResource.java
src/com/asiainfo/ocmanager/rest/resource/UserResource.java
src/com/asiainfo/ocmanager/rest/resource/executor/TenantResourceAssignRoleExecutor.java
src/com/asiainfo/ocmanager/rest/resource/executor/TenantResourceCreateInstanceBindingExecutor.java
src/com/asiainfo/ocmanager/rest/resource/executor/TenantResourceUpdateRoleExecutor.java
src/com/asiainfo/ocmanager/rest/resource/utils/TURAssignmentPersistenceWrapper.java

merge ocmanager's newest code

---

src/com/asiainfo/ocmanager/dacp/dacpForResourceUtil.java

租户资源每次请求进行初始化

---

src/com/asiainfo/ocmanager/dacp/DacpAllResult.java

	打getAllResult方法日志

---

src/com/asiainfo/ocmanager/dacp/dacpForResourceUtil.java

修改hadoop资源  解析规则

---

WebContent/WEB-INF/conf/config.properties
src/com/asiainfo/ocmanager/dacp/DBUrlEnum.java

hive kerberos认证串

---

src/com/asiainfo/ocmanager/dacp/DBUrlEnum.java
src/com/asiainfo/ocmanager/dacp/dacpForResourceUtil.java
src/com/asiainfo/ocmanager/rest/resource/quotaUtils/kafkaUtils.java

dacp hive kerberos认证信息principal修改

dacp hive kerberos认证信息principal修改

---

src/com/asiainfo/ocmanager/dacp/dacpForResourceUtil.java

dacp同步信息添加sparksql 修改shiftUri值覆盖uri值的问题

dacp同步信息添加sparksql 修改shiftUri值覆盖uri值的问题

---

src/com/asiainfo/ocmanager/rest/resource/quotaUtils/kafkaUtils.java

kafka shell 路径

---

WebContent/WEB-INF/conf/config.properties
WebContent/WEB-INF/conf/kafka_jaas_online.conf
WebContent/WEB-INF/conf/krb5_online.conf
src/com/asiainfo/ocmanager/dacp/DBUrlEnum.java
src/com/asiainfo/ocmanager/dacp/dacpForResourceUtil.java

dacp 区分hive sparksql

---

src/com/asiainfo/ocmanager/rest/DownloadUtils/GetFile.java
src/com/asiainfo/ocmanager/rest/resource/KerberosResource.java

Add some judgment in the download function

Add some judgment in the download function

---

src/com/asiainfo/ocmanager/dacp/utils/KeyTabClient.java

同步dacp生成文件

---

WebContent/WEB-INF/conf/config.properties
src/com/asiainfo/ocmanager/dacp/DacpForResourceUtil.java

dacp create keytab file and deploy to dest reservers

dacp create keytab file and deploy to dest reservers

---

WebContent/WEB-INF/conf/config.properties

Add keytabpath in config

---

WebContent/WEB-INF/conf/config.properties
src/com/asiainfo/ocmanager/dacp/DacpForResourceUtil.java

optimize code of keytab deploy to dest reservers

 optimize code of keytab deploy to dest reservers

---

src/com/asiainfo/ocmanager/dacp/Authentication.java
src/com/asiainfo/ocmanager/dacp/DFDataQuery.java
src/com/asiainfo/ocmanager/dacp/DacpAllResult.java
src/com/asiainfo/ocmanager/rest/resource/KerberosResource.java
src/com/asiainfo/ocmanager/rest/resource/downloadUtils/GetFile.java
src/com/asiainfo/ocmanager/rest/resource/quotaUtils/AmbariUtil.java
src/com/asiainfo/ocmanager/rest/resource/quotaUtils/HbaseUtil.java
src/com/asiainfo/ocmanager/rest/resource/quotaUtils/HdfsUtil.java
src/com/asiainfo/ocmanager/rest/resource/quotaUtils/YarnUtil.java

Add comments

---

src/com/asiainfo/ocmanager/rest/resource/downloadUtils/DownloadResult.java
src/com/asiainfo/ocmanager/rest/resource/downloadUtils/GetFile.java

Add DownloadResult

---

src/com/asiainfo/ocmanager/rest/resource/downloadUtils/DownloadResult.java
src/com/asiainfo/ocmanager/rest/resource/downloadUtils/GetKeytabFile.java

code to lowercase,catch update

code to lowercase,catch update
